name: Build JavaScriptCore (JSC) dynamic libs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-jsc-${{ github.ref }}
  cancel-in-progress: true

env:
  CONFIG: Release

jobs:
  build:
    name: ${{ matrix.target }}${{ matrix.abi && format(' ({0})', matrix.abi) || '' }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux host -> Linux .so
          - os: ubuntu-latest
            target: linux

          # Windows host -> Windows .dll
          - os: windows-latest
            target: windows

          # Android ABIs -> Android .so (cross-compile on Ubuntu)
          - os: ubuntu-latest
            target: android
            abi: arm64-v8a

    steps:
      - name: Checkout WebKit
        uses: actions/checkout@v4
        with:
          repository: WebKit/WebKit
          path: webkit
          fetch-depth: 1

      # ---------------------------
      # Linux 依赖
      # ---------------------------
      - name: Install deps (Linux)
        if: matrix.target == 'linux' || matrix.target == 'android'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build \
            gperf bison flex ruby perl python3 \
            pkg-config libicu-dev libxml2-dev libxslt1-dev \
            libsqlite3-dev libjpeg-dev libpng-dev libwebp-dev \
            libharfbuzz-dev ccache

      - name: Setup MSVC env (Windows)
        if: matrix.target == 'windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # ---------------------------
      # Windows 依赖
      # ---------------------------
      - name: Install deps (Windows via Chocolatey)
        if: matrix.target == 'windows'
        shell: pwsh
        run: |
          choco install -y strawberryperl cmake ninja gperf winflexbison3 python ruby nasm

      # ---------------------------
      # Android NDK
      # ---------------------------
      - name: Setup Android NDK
        if: matrix.target == 'android'
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true
          link-to-sdk: true
          local-cache:
            true

            # 新增：构建 ICU for Android
      - name: Build ICU for Android
        if: matrix.target == 'android'
        working-directory: ${{ github.workspace }}
        run: |
          git clone https://github.com/unicode-org/icu.git
          cd icu/icu4c/source
          mkdir -p build-android && cd build-android
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$PWD/install
          cmake --build . --target install
      # ---------------------------
      # Cache
      # ---------------------------
      - name: Cache WebKitBuild (incremental)
        uses: actions/cache@v4
        with:
          path: |
            webkit/WebKitBuild
          key: ${{ runner.os }}-jsc-${{ matrix.target }}-${{ matrix.abi || 'na' }}-${{ hashFiles('webkit/Tools/Scripts/build-jsc', 'webkit/Source/JavaScriptCore/**') }}
          restore-keys: |
            ${{ runner.os }}-jsc-${{ matrix.target }}-${{ matrix.abi || 'na' }}-

      # 判断缓存是否命中，跳过构建
      - name: Skip build if cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "Cache hit; skipping build"

      # ---------------------------
      # Build
      # ---------------------------
      - name: Build JSC (Linux)
        if: steps.cache.outputs.cache-hit != 'true' && matrix.target == 'linux'
        working-directory: webkit
        run: |
          Tools/Scripts/build-jsc --jsc-only --Release \
            --cmakeargs="-GNinja"

      - name: Build JSC (Android ${{ matrix.abi }})
        if: steps.cache.outputs.cache-hit != 'true' && matrix.target == 'android'
        working-directory: webkit
        run: |
          Tools/Scripts/build-jsc --jsc-only --Release \
            --cmakeargs="-GNinja \
              -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=${{ matrix.abi }} \
              -DANDROID_PLATFORM=android-24 \
              -DICU_ROOT=${{ github.workspace }}/icu/icu4c/source/build-android/install \
              -DICU_INCLUDE_DIR=${{ github.workspace }}/icu/icu4c/source/build-android/install/include \
              -DICU_LIBRARY=${{ github.workspace }}/icu/icu4c/source/build-android/install/lib/libicuuc.a \
              -DICU_I18N_LIBRARY=${{ github.workspace }}/icu/icu4c/source/build-android/install/lib/libicui18n.a \
              -DICU_DATA_LIBRARY=${{ github.workspace }}/icu/icu4c/source/build-android/install/lib/libicudata.a \
              -DCMAKE_POLICY_DEFAULT_CMP0048=NEW"

      - name: Build JSC (Windows)
        if: steps.cache.outputs.cache-hit != 'true' && matrix.target == 'windows'
        shell: pwsh
        working-directory: webkit
        run: perl Tools/Scripts/build-jsc --jsc-only --Release --cmakeargs='-GNinja'

      # ================= Upload Artifacts =================
      - name: Prepare artifacts for upload
        working-directory: webkit
        run: |
          mkdir -p artifact-dir
          tar -czf WebKitBuild.tar.gz WebKitBuild
          mv WebKitBuild.tar.gz artifact-dir/

      - name: Upload Linux artifacts
        if: matrix.target == 'linux'
        uses: actions/upload-artifact@v4
        with:
          name: jsc-linux
          path: |
            artifact-dir/WebKitBuild.tar.gz

      - name: Upload Windows artifacts
        if: matrix.target == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: jsc-windows-${{ matrix.arch }}
          path: |
            artifact-dir/WebKitBuild.tar.gz

      - name: Upload Android artifacts
        if: matrix.target == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: jsc-android-${{ matrix.abi }}
          path: |
            artifact-dir/WebKitBuild.tar.gz
